#!/bin/bash

# Advent of Code 2024 Runner Script
# Usage: ./aoc <day>
# Example: ./aoc 16

if [ $# -gt 1 ]; then
    echo "Usage: $0 [day_number]"
    exit 1
fi

DAY=$1

# Build and run the solution
dune exec bin/main.exe $DAY